name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check

      - run: cargo clippy --all-features -- -D warnings

      - run: cargo clippy --tests

      - run: cargo check

      - run: cargo check --no-default-features

      - run: cargo check --no-default-features --features serde

      - run: cargo check --no-default-features --features derive

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: cargo test
